deepspeed lerobot/scripts/dps_train.py \
        --deepspeed="./ds_zero2.json" \
        --policy.type="qwen" \
        --dataset.repo_id="whatever" \
        --dataset.processor="/datassd_1T/qwen25vl/Qwen2.5-VL-7B-Instruct/" \
        --dataset.parent_dir="/data_16T/lerobot_openx/" \
        --output_dir="/data_16T/deepseek/qwen_flow/" \
        --policy.scheduler_warmup_steps=500 \
        --policy.scheduler_decay_steps=1500 \
        --policy.optimizer_lr=1e-3 \
        --policy.train_main_layers=0 \
        --policy.freeze_vision_encoder=true